import { College, Category, Award, Testimonial } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Engineering & Technology",
    slug: "engineering",
    description: "B.E / B.Tech courses in CSE, AI&DS, ECE, Mechanical, and Civil Engineering",
    icon_name: "Cpu",
    is_active: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Medical & Dental",
    slug: "medical",
    description: "MBBS, BDS, Allied Health Sciences & Post Graduate Specializations",
    icon_name: "Activity",
    is_active: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Nursing & Pharmacy",
    slug: "nursing",
    description: "B.Sc Nursing, B.Pharm, D.Pharm & Paramedical Diploma courses",
    icon_name: "HeartPulse",
    is_active: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Law",
    slug: "law",
    description: "5-Year Integrated BA LLB / BBA LLB & 3-Year LLB programs",
    icon_name: "Scale",
    is_active: true,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "Arts & Science",
    slug: "arts-science",
    description: "B.Sc Computer Science, B.Com, BBA, B.A & Master degree programs",
    icon_name: "BookOpen",
    is_active: true,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export interface DetailedCollege extends College {
  category_slug: string;
  city: string;
  district: string;
  departments: {
    id: string;
    name: string;
    code: string;
    duration: string;
    tuitionFeePerYear: string;
    eligibility: string;
  }[];
  facilities: string[];
}

export const mockColleges: DetailedCollege[] = [
  {
    id: "col-1",
    name: "SRM Institute of Science and Technology",
    slug: "srm-ist-ramapuram",
    short_name: "SRM IST Ramapuram",
    location_id: "loc-1",
    city: "Chennai",
    district: "Chennai",
    category_slug: "engineering",
    address: "Bharathi Salai, Ramapuram, Chennai, Tamil Nadu 600089",
    established_year: 2004,
    institution_type: "Deemed University",
    affiliation: "UGC / AICTE Approved",
    accreditation: "NAAC A++ Grade",
    nirf_ranking: 28,
    description:
      "SRM Institute of Science and Technology, Ramapuram Campus, is a premier institution offering high-quality engineering and technological education with world-class laboratory infrastructure, active industry partnerships, and exceptional placement records.",
    logo_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: true,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-1",
        name: "Computer Science & Engineering",
        code: "B.Tech CSE",
        duration: "4 Years",
        tuitionFeePerYear: "₹2,50,000 / Year",
        eligibility: "10+2 with Physics, Chemistry & Math (min 60%)",
      },
      {
        id: "dep-2",
        name: "Artificial Intelligence & Data Science",
        code: "B.Tech AI&DS",
        duration: "4 Years",
        tuitionFeePerYear: "₹2,60,000 / Year",
        eligibility: "10+2 with Physics, Chemistry & Math (min 60%)",
      },
      {
        id: "dep-3",
        name: "Electronics & Communication Engineering",
        code: "B.Tech ECE",
        duration: "4 Years",
        tuitionFeePerYear: "₹2,00,000 / Year",
        eligibility: "10+2 with PCM (min 55%)",
      },
      {
        id: "dep-4",
        name: "Information Technology",
        code: "B.Tech IT",
        duration: "4 Years",
        tuitionFeePerYear: "₹2,20,000 / Year",
        eligibility: "10+2 with PCM (min 60%)",
      },
    ],
    facilities: [
      "AC Central Library",
      "High-Tech Computing Labs",
      "Boys & Girls Hostels",
      "Fleet Transport Bus Service",
      "Sports Complex & Gym",
      "24/7 Medical Care Center",
    ],
  },
  {
    id: "col-2",
    name: "PSG College of Technology",
    slug: "psg-tech-coimbatore",
    short_name: "PSG Tech",
    location_id: "loc-2",
    city: "Coimbatore",
    district: "Coimbatore",
    category_slug: "engineering",
    address: "Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641004",
    established_year: 1951,
    institution_type: "Autonomous Government Aided",
    affiliation: "Anna University",
    accreditation: "NAAC A Grade, NBA Accredited",
    nirf_ranking: 63,
    description:
      "PSG College of Technology is an autonomous, government-aided institution renowned for pioneering engineering education, industry research collaborations, innovation centers, and exceptional student placement figures across India and globally.",
    logo_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: true,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-5",
        name: "Computer Science & Engineering",
        code: "B.E CSE",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,25,000 / Year",
        eligibility: "TNEA Counseling / 10+2 PCM Cutoff",
      },
      {
        id: "dep-6",
        name: "Mechanical Engineering",
        code: "B.E MECH",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,15,000 / Year",
        eligibility: "TNEA Counseling Cutoff",
      },
      {
        id: "dep-7",
        name: "Electrical & Electronics Engineering",
        code: "B.E EEE",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,20,000 / Year",
        eligibility: "10+2 PCM TNEA Cutoff",
      },
    ],
    facilities: [
      "Heavy Machinery Labs",
      "Advanced Research Centers",
      "Separate Hostels",
      "Cafeteria & Food Courts",
      "Wi-Fi Campus",
      "Auditorium & Seminar Halls",
    ],
  },
  {
    id: "col-3",
    name: "Loyola College",
    slug: "loyola-college-chennai",
    short_name: "Loyola Chennai",
    location_id: "loc-1",
    city: "Chennai",
    district: "Chennai",
    category_slug: "arts-science",
    address: "Sterling Road, Nungambakkam, Chennai, Tamil Nadu 600034",
    established_year: 1925,
    institution_type: "Autonomous Private",
    affiliation: "University of Madras",
    accreditation: "NAAC A++ Grade (CGPA 3.55)",
    nirf_ranking: 7,
    description:
      "Loyola College Chennai is a prestigious autonomous Catholic higher education institution offering top-ranked undergraduate and postgraduate courses in Arts, Science, Commerce, and Visual Communication.",
    logo_url: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: true,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-8",
        name: "B.Sc Computer Science",
        code: "B.Sc CS",
        duration: "3 Years",
        tuitionFeePerYear: "₹48,000 / Year",
        eligibility: "10+2 with Mathematics / Computer Science",
      },
      {
        id: "dep-9",
        name: "Bachelor of Commerce",
        code: "B.Com General",
        duration: "3 Years",
        tuitionFeePerYear: "₹52,000 / Year",
        eligibility: "10+2 with Commerce & Accountancy",
      },
      {
        id: "dep-10",
        name: "B.A Visual Communication",
        code: "B.A VisCom",
        duration: "3 Years",
        tuitionFeePerYear: "₹65,000 / Year",
        eligibility: "10+2 Any Stream with Aptitude Test",
      },
    ],
    facilities: [
      "Historic Library & Archives",
      "Media Studios & Editing Suites",
      "Student Hostel",
      "Cricket & Football Grounds",
      "Placement Cell",
    ],
  },
  {
    id: "col-4",
    name: "Madras Medical College",
    slug: "madras-medical-college-chennai",
    short_name: "MMC Chennai",
    location_id: "loc-1",
    city: "Chennai",
    district: "Chennai",
    category_slug: "medical",
    address: "EVR Periyar Salai, Park Town, Chennai, Tamil Nadu 600003",
    established_year: 1835,
    institution_type: "Government Medical College",
    affiliation: "The Tamil Nadu Dr. M.G.R. Medical University",
    accreditation: "NMC Approved / NAAC Accredited",
    nirf_ranking: 11,
    description:
      "Madras Medical College is one of the oldest medical colleges in Asia. MMC provides world-class clinical training, advanced medical research facilities, and government subsidized MBBS/BDS education.",
    logo_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: false,
    is_featured: true,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-11",
        name: "Bachelor of Medicine and Bachelor of Surgery",
        code: "MBBS",
        duration: "5.5 Years",
        tuitionFeePerYear: "₹18,000 / Year (Govt Fee)",
        eligibility: "NEET UG Qualification & TN State Medical Counseling",
      },
      {
        id: "dep-12",
        name: "Bachelor of Dental Surgery",
        code: "BDS",
        duration: "5 Years",
        tuitionFeePerYear: "₹15,000 / Year",
        eligibility: "NEET UG Rank",
      },
    ],
    facilities: [
      "Multi-Specialty Rajiv Gandhi Hospital",
      "Anatomy & Pathology Labs",
      "Medical Library",
      "Resident Doctor Hostels",
    ],
  },
  {
    id: "col-5",
    name: "Government Law College",
    slug: "government-law-college-chennai",
    short_name: "GLC Chennai",
    location_id: "loc-1",
    city: "Chennai",
    district: "Chennai",
    category_slug: "law",
    address: "Pattabiram, Chennai, Tamil Nadu 600072",
    established_year: 1891,
    institution_type: "Government Law Institution",
    affiliation: "Tamil Nadu Dr. Ambedkar Law University",
    accreditation: "Bar Council of India (BCI) Approved",
    nirf_ranking: 18,
    description:
      "Government Law College Chennai is the premier historic legal institution of Tamil Nadu, producing leading judicial officers, advocates, and legal experts through affordable government law courses.",
    logo_url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: false,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-13",
        name: "Integrated B.A. L.L.B (Honours)",
        code: "B.A. L.L.B",
        duration: "5 Years",
        tuitionFeePerYear: "₹12,000 / Year",
        eligibility: "10+2 Cutoff Marks & TNDALU Counseling",
      },
      {
        id: "dep-14",
        name: "Bachelor of Laws",
        code: "L.L.B (3 Year)",
        duration: "3 Years",
        tuitionFeePerYear: "₹10,000 / Year",
        eligibility: "UG Degree in Any Discipline",
      },
    ],
    facilities: [
      "Moot Court Hall",
      "Legal Aid Clinic",
      "Law Library & Law Journals",
      "Student Hostel",
    ],
  },
  {
    id: "col-6",
    name: "Apollo College of Nursing",
    slug: "apollo-college-of-nursing-chennai",
    short_name: "Apollo Nursing",
    location_id: "loc-1",
    city: "Chennai",
    district: "Chennai",
    category_slug: "nursing",
    address: "Vanagaram to Ambattur Main Road, Chennai, Tamil Nadu 600095",
    established_year: 1992,
    institution_type: "Private Nursing College",
    affiliation: "The Tamil Nadu Dr. M.G.R. Medical University",
    accreditation: "Indian Nursing Council (INC) & TNC Approved",
    nirf_ranking: null,
    description:
      "Apollo College of Nursing provides outstanding nursing education integrated with practical hospital clinical rotations at Apollo Hospitals, training compassionate and skilled nursing professionals.",
    logo_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: true,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-15",
        name: "Bachelor of Science in Nursing",
        code: "B.Sc Nursing",
        duration: "4 Years",
        tuitionFeePerYear: "₹95,000 / Year",
        eligibility: "10+2 with Physics, Chemistry & Biology (min 50%)",
      },
      {
        id: "dep-16",
        name: "General Nursing & Midwifery",
        code: "GNM",
        duration: "3 Years",
        tuitionFeePerYear: "₹65,000 / Year",
        eligibility: "10+2 Any Stream (min 45%)",
      },
    ],
    facilities: [
      "Apollo Multispecialty Clinical Training",
      "Simulation & Skills Labs",
      "Safe On-Campus Girls Hostel",
      "Placement Guarantee in Apollo Hospitals",
    ],
  },
  {
    id: "col-7",
    name: "SASTRA Deemed University",
    slug: "sastra-university-thanjavur",
    short_name: "SASTRA Thanjavur",
    location_id: "loc-3",
    city: "Thanjavur",
    district: "Thanjavur",
    category_slug: "engineering",
    address: "Tirumalaisamudram, Thanjavur, Tamil Nadu 613401",
    established_year: 1984,
    institution_type: "Deemed University",
    affiliation: "UGC / AICTE Approved",
    accreditation: "NAAC A++ Grade",
    nirf_ranking: 34,
    description:
      "SASTRA Deemed University is renowned for academic excellence, state-of-the-art research laboratories, high-impact placements, and disciplined academic environment.",
    logo_url: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: false,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-17",
        name: "Computer Science & Engineering",
        code: "B.Tech CSE",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,70,000 / Year",
        eligibility: "JEE Main + 10+2 Marks Normalized Cutoff",
      },
      {
        id: "dep-18",
        name: "Bio-Technology",
        code: "B.Tech Biotech",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,60,000 / Year",
        eligibility: "10+2 with Physics, Chemistry & Biology/Math",
      },
    ],
    facilities: [
      "Advanced Computing Centers",
      "Central Library",
      "Hostel for Boys and Girls",
      "Indoor Sports Complex",
    ],
  },
  {
    id: "col-8",
    name: "National Institute of Technology Tiruchirappalli",
    slug: "nit-trichy",
    short_name: "NIT Trichy",
    location_id: "loc-4",
    city: "Tiruchirappalli",
    district: "Tiruchirappalli",
    category_slug: "engineering",
    address: "Tanjore Main Road, National Highway 67, Tiruchirappalli, Tamil Nadu 620015",
    established_year: 1964,
    institution_type: "Institute of National Importance",
    affiliation: "Autonomous MHRD",
    accreditation: "NAAC A++ Grade",
    nirf_ranking: 9,
    description:
      "NIT Tiruchirappalli is India's top-ranked National Institute of Technology, offering premier engineering programs with top national rankings, campus placements, and global research recognition.",
    logo_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=1200&q=80",
    hostel_available: true,
    transport_available: true,
    is_featured: true,
    is_verified: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    departments: [
      {
        id: "dep-19",
        name: "Computer Science & Engineering",
        code: "B.Tech CSE",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,40,000 / Year",
        eligibility: "JEE Main Entrance Score & JoSAA Counseling",
      },
      {
        id: "dep-20",
        name: "Electronics & Communication Engineering",
        code: "B.Tech ECE",
        duration: "4 Years",
        tuitionFeePerYear: "₹1,40,000 / Year",
        eligibility: "JEE Main Rank",
      },
    ],
    facilities: [
      "Supercomputing Facility",
      "800-acre Wi-Fi Campus",
      "20+ Student Hostels",
      "Olympic Swimming Pool & Sports Complex",
    ],
  },
];

export const mockAwards: Award[] = [
  {
    id: "award-1",
    title: "Best Educational Guidance Platform 2025",
    organization: "Tamil Nadu Education Leadership Forum",
    year: 2025,
    description: "Recognized for transparent counselling and helping thousands of students secure college admissions across Tamil Nadu.",
    image_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "award-2",
    title: "Excellence in Student Counselling Award",
    organization: "South India Higher Education Summit",
    year: 2024,
    description: "Awarded for outstanding ethical guidance, course mapping, and career orientation for higher secondary students.",
    image_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "test-1",
    author_name: "Karthik R.",
    author_role: "Engineering Student",
    quote: "College Guide helped me understand cutoff trends and choose B.Tech CSE in a top Chennai college. Their expert team guided me through every step!",
    college_name: "SRM IST Ramapuram",
    course_name: "B.Tech CSE",
    avatar_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "test-2",
    author_name: "Subhashini M. (Parent)",
    author_role: "Parent",
    quote: "As a parent from Madurai, finding a safe college hostel and good Nursing course in Chennai was stressful until we spoke with College Guide's counsellors.",
    college_name: "Apollo Nursing",
    course_name: "B.Sc Nursing",
    avatar_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
  },
];
